services:
  - type: web
    name: traveller-backend
    env: java
    plan: free
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/traveller-backend-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-11-openjdk-amd64
